### ISSUE TITLE
Possible typo in requirements.txt naming

### ISSUE THREAD

**Issue by hydrosquall** [jupyter/repo2docker#138]
Per @betatim's comment on : https://github.com/jupyter/repo2docker/pull/83#discussion_r150372391

It is a little bit unusual that the presence of a python 2.7 runtime would lead to usage of a file called `requirements3.txt`, as I would think from reading a small section of code that `requirements3.txt` is for a python 3+ runtime.

**Comment by choldgraf** [comment]
Hmmm, after digging a bit, we've got this comment in there:

https://github.com/jupyter/repo2docker/blob/093184b36a0aeffe601d1d529539d8d7fbcf8467/repo2docker/detectors.py#L506

so it seems like this is in some sense expected behavior, as as `requirements3.txt` should be installed into the python3 venv, and `requirements2.txt` should be installed into the python 2 venv. However it's a little unclear to me how exactly that process happens and thus a bit hard to debug to make sure it's behaving as expected. Did you run into errors where `requirements.txt` was not being installed into a python 2 venv?

**Comment by hydrosquall** [comment]
@choldgraf - I belatedly noticed that comment too! After poking around a bit, it looks like both of these functions named `setup_assembly` (the one we've linked to and 

https://github.com/jupyter/repo2docker/blob/093184b36a0aeffe601d1d529539d8d7fbcf8467/repo2docker/detectors.py#L622

... are both responsible for installing `pip` dependencies. This can likely be closed, since the `requirements.txt` I setup installed everything I needed in my example with a `runtime.txt` of python 2.7. 

Thanks for looking into this!

**Comment by choldgraf** [comment]
no problem! thanks for bringing it up!
