### ISSUE TITLE
I can't get widgets to work in python2 kernels in images built by repo2docker

### ISSUE THREAD

**Issue by AaronWatters** [jupyter/repo2docker#184]
This repository:

https://github.com/simonsfoundation/jp_svg_canvas

attempts to use an `environment.yml` to set up a python 2 kernel with widgets enabled.

The image built by repo2docker results in a python 3 kernel with working widgets but widgets do not work in the python 2 kernel

<img width="596" alt="screen shot 2018-01-03 at 4 24 30 pm" src="https://user-images.githubusercontent.com/13857252/34541298-aabddab0-f0a5-11e7-837e-18349530d365.png">

 I also tried other ways to get widgets working under repo2docker in Python 2 kernels, but I'm not having any luck :(.

**Comment by AaronWatters** [comment]
The problem is that the py3 env has an older version of widgetsnbextension than the py2 env (which gets the latest available from conda, I think).  A work around is to add the following line to https://github.com/simonsfoundation/jp_svg_canvas/blob/master/postBuild
```bash
conda update -y ipywidgets widgetsnbextension
```

Maybe add this do the documentation?  Or make it unnecessary somehow?

**Comment by minrk** [comment]
Right now, widgets aren't installed in the Python 2 env. Try adding `ipywidgets` to your environment.yml. I think we should probably add that to the default, too.

**Comment by AaronWatters** [comment]
Widgets were in the environment.yml for py2.  That brought in the latest widget versions for py2 which was incompatible with the version installed in the py3 environment (where jupyter lives).  The work-around was to upgrade the widgets in the py3 environment in the postBuild.

**Comment by betatim** [comment]
Tried to make a minimal example for this to reproduce the bug. So I made [this repo](https://github.com/betatim/binder-widgets-py2/tree/b54041929c7c8353b5f2544cf08fa857e5f9be2c) which contains nothing but a `runtime.txt` with python-2.7 in it. When I launch a binder the only kernel available is Python 3. Discuss this: #280)

If you then add a `requirements.txt` you do get a Python 2 kernel. For this repo I added `ipywidgets` in `requirements.txt`.

I then added a `Button` widget in a notebook, which [seems to work](https://mybinder.org/v2/gh/betatim/binder-widgets-py2/750a6d7408f3a92c682c3b30d4f511195bbcf6a4). 

Same with an `environment.yml` instead of `runtime.txt`+`requirements.txt`: https://github.com/betatim/binder-widgets-py2/tree/f7a3e3fdb962a5ec317efdbec92676fdc96c9a0d this also seems to work.

From my side this means "can't reproduce any more" -> got fixed. @AaronWatters could you confirm that the problem has gone away?

**Comment by AaronWatters** [comment]
problem has gone away
