### ISSUE TITLE
Update docs to reflect latest buildpacks and Python 2 build specification

### ISSUE THREAD

**Issue by willingc** [jupyter/repo2docker#285]
Post merge of #284 and #277, we should test the various combinations of Python 2 build specifications to make sure that we can articulate which files take precedence when any combination of these:

- `runtime.txt`
- `requirements.txt`
- `environment.yml`

It would be helpful to document these combinations and results and also update any related binder-examples builds.

cc @betatim @choldgraf @GladysNalvarte

**Comment by choldgraf** [comment]
+1 -  I think doing some QA on the repo documentation and making sure we're up-to-date on the suggested workflows is a good idea

**Comment by jzf2101** [comment]
Are we still not certain which takes precedence?

**Comment by betatim** [comment]
I don't think anyone has worked on this, so no new knowledge :(

**Comment by jzf2101** [comment]
From what I can tell, one cannot install python directly in a `requirements.txt`.  Given the fact that we have already documented that `requirements.txt` is superceded by `environment.yml` the question to me is does `environment.yml` supercede `runtime.txt`.  This is what I'm going to do to close this issue.

**Comment by willingc** [comment]
Correct @jzf2101 that one cannot specify a Python version in requirements.txt.

Thanks for testing the different combinations. Do you think it makes sense to document:

> In fact, if environment.yml does not specify a version of Python- it defaults to 3.6 even when a runtime.txt says a different version.

**Comment by jzf2101** [comment]
@willingc That's in the PR #338

**Comment by betatim** [comment]
I think all what you said is correct in terms what wins over what.

Most of this is because we have a [list of build packs](https://github.com/jupyter/repo2docker/blob/9803f9f0cf115d33d8d983521dbf9ee7df0874e7/repo2docker/app.py#L64-L77) which are tried in turn till one says ["Jupp I match"](https://github.com/jupyter/repo2docker/blob/9803f9f0cf115d33d8d983521dbf9ee7df0874e7/repo2docker/app.py#L595-L601) and then that buildpack is used. Which is why I was saying in #338 that we should be careful with the "composable" thing because really there is only one buildpack that wins in the end, but that buildpack might support using several config files :-/
