### ISSUE TITLE
Versions of Notebook and JLab don't match conda buildpack?

### ISSUE THREAD

**Issue by jzf2101** [jupyter/repo2docker#337]
I just built https://github.com/binder-examples/conda to test the latest version of Docker with r2d.

However, the image I built uses Notebook `5.2.2` and JLab `alpha release
version: 0.30.6`.  People would probably feel more comfortable having a beta version since we're saying beta is better for general use.  

At the same time, neither version matches https://github.com/jupyter/repo2docker/blob/master/repo2docker/buildpacks/conda/environment.yml

Where are these versions coming from?

Related to #336

**Comment by betatim** [comment]
When I launch  https://github.com/binder-examples/conda  on mybinder.org I get notebook 5.4.1 according to Help -> About. JupyterLab is version 0.31.5 according to the help menu there.

**Comment by jzf2101** [comment]
That's really strange.  is binder using a version not available on pypi?

**Comment by betatim** [comment]
The version of `repo2docker` on PyPi is very old. So old that I assumed you meant `master` when you said "the latest version". mybinder.org tries to run master at all times, it falls behind a bit when we don't keep up with making deployments.

I'd even like to recommend in general that people use r2d from master because we are so slow at making releases. But that seems like a hard sell.

**Comment by jzf2101** [comment]
Do we want to cut a new release or encourage people to install from master?
