### ISSUE TITLE
Re-add jupyterhub into default installs

### ISSUE THREAD

**Issue by bitnik** [jupyter/repo2docker#458]
Since https://github.com/jupyter/repo2docker/pull/111 jupyterhub is not installed by default with repo2docker. Because BinderHub doesn't require jupyterhub in images since https://github.com/jupyterhub/binderhub/pull/110. 

But now BinderHub supports authentication (https://github.com/jupyterhub/binderhub/pull/666) and it makes sense to add jupyterhub into default installations again. Because when authentication is enabled, notebook server should be aware of the hub, so hub can start/stop it with default hub home actions and users don't need a token to reach a running server (if logged out).

What do you think?

(I was thinking to install jupyterhub in appendix but it doesn't effect custom docker images)

**Comment by betatim** [comment]
Which part of JupyterHub do we need? I think it is the `HubAuth` part right? This means we can' be pretty conservative with changing the image repo2docker produces because that part of JupyterHub  doesn't change a lot (hopefully).

> users don't need a token to reach a running server (if logged out).

What do you mean with this? You always need a token to access the single user notebook server no?

> (I was thinking to install jupyterhub in appendix but it doesn't effect custom docker images)

For custom `Dockerfiles` there isn't much repo2docker can do beyond writing in the documentation that you should install it. I think.

**Comment by bitnik** [comment]
> Which part of JupyterHub do we need?

I think we need `jupyterhub-singleuser ` command (https://github.com/jupyterhub/jupyterhub/blob/master/scripts/jupyterhub-singleuser) and yes that requires `HubOAuth`.

> You always need a token to access the single user notebook server no?

I think you don't need it if you start user server with `jupyterhub-singleuser` command.

This issue (https://github.com/jupyterhub/binderhub/issues/103) is very related to what I am trying to say (but not sure if it supports me)

**Comment by betatim** [comment]
My understanding: access to the singleuser notebook server is always authenticated via a token. In JupyterHub the single user server (via `jupyterhub-singleuser`) checks with the hub to establish if the token the user presented is valid. In Binder we configure the token explicitly (via `--NotebookApp.token=xyz`) when starting the pod. The value of the token is set by BinderHub in the user's browser.

I've not followed the BinderHub with authentication PR closely enough to understand how auth works there and if my above statement is still true or not. I'll do some reading or maybe someone who has a good overview can comment here.

**Comment by yuvipanda** [comment]
BinderHub runs a special set of commands that use token auth, make it not require the `jupyterhub-singleuser` command to be in the repo, since we don't need any authentication. I'd support re-adding jupyterhub to the core since I'm guessing you need `jupyterhub-singleuser` for the normal JupyterHub <-> SingleUser authentication to work.
