### ISSUE TITLE
Set jupyter-notebook password on Google Cloud

### ISSUE THREAD

**Issue by mhlr** [jupyter/repo2docker#542]
I am trying to use repo2docker to deploy a repo with a jupyter notebook to Google cloud.
I am able to use docker2repo to run a docker container locally.
When I deploy to Google cloud I get asked for an authentication token.
Which I do not have since I did not see the output when the gcp instance started.
I have tried putttin a ./jupyter-notebook-config.py and a .jupyter/jupyter-notebook-config.py
with a known password at the root of my repo and rebuilding & pushing the image and then starting a new GCP instance based on the image, but it still want a token and the password from the config file does not work.

How do I build a docker image with a notebook server that uses a known password?

**Comment by betatim** [comment]
In principle, the approach you took should work.

I think the name of the configuration file should be `jupyter_notebook_config.py` (you have `-` instead of `_`). Does that already fix your problem?

I'm not familiar with launching docker containers on GCP. Could you give a short example of what commands you typed and which of the many GCP services you use?

**Comment by mhlr** [comment]
Thanks @betatim, I actually do have the correct filename in my repo, I just mistyped it here.

Currently I do
jupyter-repo2docker -P --image-name test1 ~/test1
docker push us.gcr.io/first-volley/test1

and then I use the gcp web interface to launch an a docker based instance
![image](https://user-images.githubusercontent.com/1808573/50679732-52e41300-0fca-11e9-8216-6e714b80bea8.png)

**Comment by betatim** [comment]
Thanks! I didn't know you could ask GCP VMs to directly launch a container for you (every day is a school day).

Is there a way to obtain the log at all for debugging?

Otherwise I'd try and debug it locally by running `docker run test1` (my guess this is what GCP does) as a way to get access to the stdout.

Off the top of my head I can't think of why this should be a problem in `repo2docker` directly. It is probably a mixture of the exact command that is executed (if you run `repo2docker --debug ...` you can see the Dockerfile used to build the image and the command we run), search path setups or something like that. That is where I'd investigate.

**Comment by mhlr** [comment]
@betatim 
This is getting stranger. When I run the initial jupyter-repo2docker command a container gets started that has the right password and I can do work in. When I start it with `docker run test1` It appears to start in the console and I see it with `docker ps` but there is nothing on 127.0.0.1:8888


$ docker run test1
[I 10:18:15.243 NotebookApp] Writing notebook server cookie secret to /home/dm/.local/share/jupyter/runtime/notebook_cookie_secret
[W 10:18:15.434 NotebookApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[I 10:18:15.440 NotebookApp] Appmode server extension loaded.
[I 10:18:15.467 NotebookApp] JupyterLab extension loaded from /srv/conda/lib/python3.6/site-packages/jupyterlab
[I 10:18:15.467 NotebookApp] JupyterLab application directory is /srv/conda/share/jupyter/lab
[I 10:18:15.478 NotebookApp] nteract extension loaded from /srv/conda/lib/python3.6/site-packages/nteract_on_jupyter
[I 10:18:15.479 NotebookApp] Serving notebooks from local directory: /home/dm
[I 10:18:15.479 NotebookApp] The Jupyter Notebook is running at:
[I 10:18:15.479 NotebookApp] http://(eafad545e391 or 127.0.0.1):8888/
[I 10:18:15.480 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 10:18:15.480 NotebookApp] No web browser found: could not locate runnable browser.
```

```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
d6644e210533        test1               "jupyter notebook --…"   7 seconds ago       Up 5 seconds        8888/tcp                 quizzical_lamarr
```

```
$ nmap -P0 127.0.0.1

Starting Nmap 7.60 ( https://nmap.org ) at 2019-01-04 04:34 CST
Nmap scan report for localhost (127.0.0.1)
Host is up (0.000073s latency).
Not shown: 996 closed ports
PORT     STATE SERVICE
80/tcp   open  http
631/tcp  open  ipp
5000/tcp open  upnp
9050/tcp open  tor-socks

Nmap done: 1 IP address (1 host up) scanned in 0.07 seconds
```

/shrug

**Comment by betatim** [comment]
If you use `docker run` you need to explicitly list the ports to forward, `repo2docker` sets that up for you. I think `docker run -p 8888:8888 test1` will expose the correct port.
