### ISSUE TITLE
RTD webhook setup

### ISSUE THREAD

**Issue by betatim** [jupyter/repo2docker#584]
Could someone check the webhook integration on this repository for read the docs? See https://github.com/jupyterhub/jupyterhub/issues/2427

The last build of the r2d docs was on 16th January 2019, which seems a long time ago though I don't know how to determine when the last build should have been (is RTD smart enough to know when nothing has changed in the docs when we merge a PR?).

**Comment by betatim** [comment]
I think the webhook isn't working properly as the last build of `master` was a month ago but we merged changes to the docs yesterday in #583.

**Comment by betatim** [comment]
This needs @willingc or @minrk (I think) as you are the ones with enough privilege to look at the webhook configuration of this repository.

**Comment by willingc** [comment]
Added webhook. 

### How to update

- Follow [RTD webhook directions](https://docs.readthedocs.io/en/latest/webhooks.html#github)
- Any maintainer listed on RTD should be able to go into Admin-> Integrations and get the webhook URL
- You will need privileges on the GitHub repo, go into Settings -> Webhooks and add the webhook
- Check on RTD that the webhook gave a 200 on its test ping. (Found on the RTD Admin-> Integrations -> webhook)
- Relaunch a Build manually on RTD. Builds -> Latest -> Build Version. 
- Verify build. *Note: this step should be done after every doc PR merge.*

*This will need to be done for every repo that has not yet been updated with a webhook in GitHub. This is necessary since Services were deprecated in GitHub.*

**Comment by betatim** [comment]
Abusing this issue a bit as a todo list. Below the repos I've checked or tried to check. For those that I can't check I've left my name as a sign that I tried but can't (and won't check). If you are reading this please see if you can check :)

* https://github.com/jupyterhub/binderhub
   * [x] checked
   * [x] works
* repo2docker
   * [x] checked
   * [x] works
* https://github.com/jupyterhub/mybinder.org-deploy
    * [ ] checked (Tim can't check)
    * [ ] works
* jupyterhub/binder
    * [x] checked
    * [x] works
* https://github.com/jupyterhub/team-compass/
    * [ ] checked (Tim can't)
    * [ ] works

**Comment by choldgraf** [comment]
@betatim since all of your boxes are checked, can we close this one?

**Comment by betatim** [comment]
Thanks everyone who helped out with this tedious task!
