### ISSUE TITLE
python>=3.6 in environment.yml causes 500: Internal Server Error

### ISSUE THREAD

**Issue by pwrose** [jupyter/repo2docker#618]
When an environment.yml file with python>=3.6 is used, binder builds and launches ok, however, when I try to run a notebook I get the error: 500 : Internal Server Error.

Thanks @betatim for pointing out that this may be related to the tornado version (works with tornado<=6.0 or python==3.6).

Example environment.yml file that reproduces this issue:
```
name: test
  
dependencies:
  - python>=3.6
  - numpy
```

**Comment by betatim** [comment]
I think what happens is that having a specification like `python>=3.6` allows conda to re-evaluate all constraints and as a result it also updates (because it can) all packages. This means you get the latest version of the notebook which depends on tornado 6.

I thought we had a bug related to this ("suddenly all packages get updated") and change the conda command(s) we use to prevent this from happening as much as possible.

**Comment by betatim** [comment]
I think #627 should fix this. Closing for now.
