### ISSUE TITLE
repo2docker v0.9.0 is incompatible with ruamel.yaml 0.16 

### ISSUE THREAD

**Issue by renefritze** [jupyter/repo2docker#755]
### Bug description

[ruamel.yaml](https://pypi.org/project/ruamel.yaml/) released 0.16 on 2019/7/25 
repo2docker 0.9.0 breaks with
```
Traceback (most recent call last):
  File "/usr/bin/repo2docker", line 6, in <module>
    from repo2docker.__main__ import main
  File "/usr/lib/python3.7/site-packages/repo2docker/__main__.py", line 6, in <module>
    from .app import Repo2Docker
  File "/usr/lib/python3.7/site-packages/repo2docker/app.py", line 31, in <module>
    from .buildpacks import (
  File "/usr/lib/python3.7/site-packages/repo2docker/buildpacks/__init__.py", line 2, in <module>
    from .python import PythonBuildPack
  File "/usr/lib/python3.7/site-packages/repo2docker/buildpacks/python/__init__.py", line 4, in <module>
    from ..conda import CondaBuildPack
  File "/usr/lib/python3.7/site-packages/repo2docker/buildpacks/conda/__init__.py", line 6, in <module>
    from ruamel.yaml import YAML
ImportError: cannot import name 'YAML' from 'ruamel.yaml' (/usr/lib/python3.7/site-packages/ruamel/yaml/__init__.py)

```

Edit: [Full log from our CI](https://zivgitlab.uni-muenster.de/pymor/pymor/-/jobs/175763)

**Comment by betatim** [comment]
Thanks for posting this. For me in a new conda environment with Python 3.7 the following works:
```
$ git clone https://github.com/jupyter/repo2docker
$ cd repo2docker
$ pip install -e.
$ repo2docker --no-run https://github.com/binder-examples/conda
```
this it has ruamel.yaml v0.16 installed. Could you confirm that this works for you too?

I don't think there is anything we can do for repo2docker 0.9.0. For the future we should think about specifying our dependencies in a way that doesn't select a newer version. In the meantime you can install ruamel explicitly and select a version before the current release.

We will probably make a new release in a few weeks (it has been roughly three months since the last release). We run `master` on mybinder.org a few hours after changes get merged into repo2docker so you should be fine running a (very) new version of repo2docker as well.

**Comment by renefritze** [comment]
> you should be fine running a (very) new version of repo2docker as well.

ATM, for our CI, I'm fine with repo2docker 0.9.0 and just installing the last working ruamel.yaml by hand before installing repo2docker.
https://github.com/pymor/pymor/pull/744/commits/af48c10f4c139151db85a45cdccb8cbccc4221f8#diff-230a826add32c4291a3519afe43ef745R145



> Could you confirm that this works for you too?

Don't have conda on my machine, but this works with a virtualenv, yes.

**Comment by betatim** [comment]
Glad installing a ruamel version by hand works for you.

Should we close this>

**Comment by renefritze** [comment]
Alright.
