### ISSUE TITLE
404 page shown during build when pointing to a repo

### ISSUE THREAD

**Issue by davidanthoff** [jupyter/repo2docker#761]
I have a binder repo [here](https://github.com/davidanthoff/teaching-2019-aere-workshop). When people click on the "Launch binder" button, they see this:

![image](https://user-images.githubusercontent.com/1036561/62801724-3695e080-ba9b-11e9-9117-ecab12183fb1.png)

Which is really not ideal because then they think that something went wrong and that there is some bug, when in fact everything is fine.

I think the reason it looks that way is that I'm actually not linking to a specific notebook, but instead just to the whole repo. I think in that case it would be better to not show a 404 link during build, but something that looks less scary and that doesn't look like something went wrong.

**Comment by betatim** [comment]
Thanks for reporting this. Could we close the issue here and move it to https://github.com/jupyterhub/binderhub? Unfortunately I can't move it across organisations on GitHub :(

There should already be an issue in the BinderHub repository discussing if we can detect if the nbpreview would show something useful or not and only if it would show it, otherwise hide it.

**Comment by davidanthoff** [comment]
Alright, opened my issue over there, @betatim can you open your response over there as well? And thanks for the workaround, that fixes things for us now!
