### ISSUE TITLE
[Feature Request] Python Library API for repo2docker

### ISSUE THREAD

**Issue by ljvmiranda921** [jupyter/repo2docker#814]
Hello everyone, thank you for building repo2docker, it is such an awesome tool!

### Proposed change

I am wondering if it's possible to have a Python library with a consistent design so that it is possible to call repo2docker programmatically whenever we build applications on top of it. Ideally, it would be helpful for us developers to create a base template of the Dockerfile then put the repo and its corresponding environment in between.

### Alternative options

I believe it's possible to do that with the current API and by just looking at `app.py`, but perhaps a good documentation on how to call these methods programmatically will be very sufficient. I know that `repo2docker` was created as a command-line tool first, but would be nice to use it as a library.

### Who would use this feature?

Mostly developers who want to include the repo2docker functionality "natively" in their applications. Currently the way I do it is I just run shell commands within Python that invoke `repo2docker`

### How much effort will adding it take?

This might require some updates in the library and some refactors, so this might take a bit of effort. However, I'm very happy to help as long as you show me the way!

**Comment by betatim** [comment]
Could you explain a bit more what is missing from the `Repo2docker` class defined in `app.py`? Like you say, you can already use this as a library. This is also how repo2docker the CLI works. It creates an instance, configures it and then runs things.

Is it mostly about creating more documentation or have you found things where using it as a library like this doesn't work well (for example instances where we call `sys.exit()` instead of raising an exception).

**Comment by betatim** [comment]
Closing as there hasn't been any activity for a while. Feel free to reopen if you want to restart this.
