### ISSUE TITLE
Allow specifying requirements file location

### ISSUE THREAD

**Issue by stefanv** [jupyter/repo2docker#853]
For scikit-image, we host the various versions of our documentation inside a single repo.  We do this so that they render as `https://scikit-image.org/docs/0.16.x/`, `https://scikit-image.org/docs/0.15.x/`, etc.

We would like to add binder links to our example notebooks, but for each version of the docs, we need a different version of scikit-image.  So, we would like to launch an image that fetches its requirements from, say, `0.16.x/requirements.txt`.

Currently, requirements can be specified per repo, or per branch, but no specific location can be provided.

What do you think about allowing specifying the requirements path, instead of expecting it in a fixed location?

**Comment by manics** [comment]
You might find this related issue on BinderHub relevant: https://github.com/jupyterhub/binderhub/issues/1030
It concerns building subdirectories of monorepos but it raises similar issues in terms of the user interface on mybinder.

**Comment by betatim** [comment]
I see the use case and sometimes have it myself but I don't see how we can keep the simple (though for a lot of people already very complex) URLs we have right now for launching a binder and integrate functionality like this.

My recommendation would be to look at what scikit-learn did when they integrated binder badges into their example gallery. The badge on https://scikit-learn.org/dev/auto_examples/plot_changed_only_pprint_parameter.html#sphx-glr-auto-examples-plot-changed-only-pprint-parameter-py and https://scikit-learn.org/stable/auto_examples/plot_changed_only_pprint_parameter.html#sphx-glr-auto-examples-plot-changed-only-pprint-parameter-py go to different branches of the repository.

I'm trying to remember who did the work of creating the integration but I can't :( Searching for mybinder.org or binder in https://github.com/scikit-learn/scikit-learn will probably find the issues/PRs. It started out with a fairly complex setup but as we iterated we managed to arrive at what is there now which looks nice and I think avoids a lot of complex CI magic to push around branches and clone repos that were part of the first solution.

**Comment by stefanv** [comment]
Looking at that URL, I can't quite figure out where their notebooks live.  The URL includes `gh/scikit-learn/scikit-learn`, then later `lab/tree/...`.  Does the `lab` part have some magical meaning?

In terms of making this simple, perhaps allow specification of a "root" argument, i.e. have binder pretend that the repo root is at that path, instead of at the actual root.

**Comment by betatim** [comment]
`lab/tree...` ends up in the URL because scikit-learn wants users to use JupyterLab.

I don't think scikit-learn has notebooks in their repo, instead they generate them from their example gallery when the [repo is being built](https://github.com/scikit-learn/scikit-learn/blob/master/.binder/postBuild).

I don't know which tool/plugin they use but the binder links in their docs for different versions use different branches of the repository. This is how they solve the problem of having different requirements for different versions of scikit-learn.

**Comment by betatim** [comment]
I don't think I am doing a great job explaining what I mean so I will make a PR to the scikit-image repo with a proposal.

**Comment by stefanv** [comment]
I think that solution could work for us too; our need was to have different versions of requirements.txt, and that is addressed by building the notebooks from source "on the fly".

**Comment by stefanv** [comment]
(You can go ahead and close the issue, if you want.  I still think this would be a valuable feature: it would prevent people from having to jump through post-build hoops like described above, and I don't think it's unreasonable to want to host multiple setups in one repo.)

Thanks again for helping us out with a solution!

**Comment by betatim** [comment]
For people from the future: the scikit-image setup is a bit a-typical. This is why things are a bit more complex. The `postBuild` acrobatics are related to using sphinx-gallery and converting the `.py` examples to notebooks. Not to wanting to have different `requirements.txt` for different versions, this is done via branches.

**Comment by stefanv** [comment]
If someone could show us how to render branches as `https://scikit-image.org/doc/{branch_name}`, that would also solve our problem!  But, as far as I know, that is not currently supported by GitHub pages.  Hence, almost every scientific Python project has to do the same thing.

See, e.g., https://github.com/numpy/doc

**Comment by betatim** [comment]
This sounds like there is something I don't understand/misunderstand. 

The problem I thought we were trying to solve is that you want to build different docker images for different versions of scikit-image. So that from the docs for version 0.16 you can link to the examples for v0.16 and let users execute them against v0.16 as well. In the docs for v0.15 you want to send people to a binder environment with 0.15 installed and the examples as they were for v0.15.

This we can solve by having mybinder.org/v2/gh/org/repo/0.16/...stuff... and mybinder.org/v2/gh/org/repo/0.15/...stuff... links in the respective versions of the docs.

I don't understand what you mean with "how to render branches as `https://scikit-image.org/doc/{branch_name}`". How do you currently build your documentation? https://scikit-image.org/docs/0.15.x/ and https://scikit-image.org/docs/0.16.x/ point to different versions of your docs which sounds like what you want?

**Comment by stefanv** [comment]
Yes, it can be solved that way, but it would be a duplication of the existing workflow, which already publishes the notebook files—albeit to a single repository.  This is why the workaround here is a post-processing step, that re-generates the notebooks (that we already have, in our online documentation).  We'd prefer to re-use the copy that is there.

To clarify how URLs are resolved right now: all docs live in the [docs](https://github.com/scikit-image/docs/tree/gh-pages) repo under different subdirectories.  GitHub pages render these at https://scikit-image/org/docs, so, via subdirectories we get to the different versions.

As far as I know, there is currently no mechanism to tell GitHub pages to render different branches to different URLs.

**Comment by betatim** [comment]
The scikit-image gallery now has binder badges so closing this.
