### ISSUE TITLE
nixpkg-unstable channel requires nix>=2.2

### ISSUE THREAD

**Issue by jboynyc** [jupyter/repo2docker#911]
### Bug description

I initially filed this bug [here](https://github.com/jupyterhub/binderhub/issues/1110). Trying to launch Binder with a repo containing a `default.nix` file currently fails because adding the nixpkg-unstable channel (which happens [here](https://github.com/jupyter/repo2docker/blob/master/repo2docker/buildpacks/nix/__init__.py#L64)) requires nix>=2.2 but repo2docker's is [pinned](https://github.com/jupyter/repo2docker/blob/master/repo2docker/buildpacks/nix/install-nix.bash#L5) to version 2.1.1.

#### Expected behaviour

Build an image that can run nix-shell.

#### Actual behaviour

Building the image fails.

### How to reproduce

Try to start Binder using the Github repository jboynyc/textnets or any other that contains `default.nix` and hasn't had an image created for it yet.

**Comment by betatim** [comment]
Is there something we should consider before moving from 2.1 to 2.2? Are there things that used to work in 2.1 and now stopped working that would break repos which are currently working if we upgrade?

Otherwise this would be a good issue to get started on contributing to repo2docker by updating the nix version pin to 2.2.

Thanks for reporting this! repo2docker uses several build tools and the maintainers only use a subset of those daily. This means we rely on keen users to help us stay on top of best practices and going ons in the sub-communities.

**Comment by jboynyc** [comment]
I'll try to find out!

**Comment by jboynyc** [comment]
I took a swing at it @betatim. After studying previous commits and nix change logs, I couldn't find any reason for sticking with the old version.

**Comment by jboynyc** [comment]
#915 closes this issue after [this commit](https://github.com/jupyter/repo2docker/commit/8bbced7ded5a21b581f1f3846ffc9f87944ba799).
